# YouTube / Browser PiP
windowrule {
    name = zen-pip

    match:title = ^(Picture-in-Picture)$
    match:class = ^(zen)$

    float = true
    pin = true
    stay_focused = false

    size = 430 240
    move = 100%/5 100%-240
}
