###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = pgrep -x wofi && pkill -x wofi || wofi --show
$mainMod = SUPER

env = XDG_MENU_PREFIX,arch
